### ISSUE TITLE
Test only passes without closing tags.

### ISSUE THREAD

**Issue by Madeline-Stark** [learn-co-students/html-fundamentals-html-lists-lab-online-web-prework#24] opened 2019-07-11 17:34 UTC
Students have been taught to close li tags, but the tests only pass without them. 
Example:
<li>cheddar

**Comment by baschenbrenner** [comment] 2019-08-17 15:35
I went through and fixed the spec for a student that was having a similar problem. He had a chrome book. Not sure what the issue is or why the differences were necessary


RSpec.describe 'index.html' do
  it 'contains a <ul> tag with the correct <li> tags' do
    ul = parsed_html.search('ul').first
    expect(ul).to_not be_nil, "The main <ul> tag is missing!"
    expect(html_file_contents).to include('</ul>'), "Don't forget to include a closing </ul>"

    children = ul.children.select {|child| child.name == "li"}
    expect(children.length).to be >= 3, "Your <ul> tag needs at least three <li> tags, one for each ingredient"
    expect(children[0].text).to match("2 slices of bread")
    expect(children[1].text).to match("4 slices of cheese")
    expect(children[2].text).to match("1 tbsp of butter")
  end


  it 'contains a nested <ul> tag' do
    ul = parsed_html.search('ul').first
    children = ul.children.select {|child| child.name == "li"}
    subchildren = children.select {|child| child.children.length > 0}
    nested_ul = subchildren.any? {|sc| sc.children.any? {|ch| ch.name == "ul"}}
    nested_children = subchildren.select {|sc| sc.children.any? {|ch| ch.name == "ul"}}.select {|sc| sc.children.length > 1}

    expect(nested_ul).to be ==  true
    expect(nested_children[0].children[1].children.length).to be >= 3 
  end

  it 'contains a <ol> tag' do
    ol = parsed_html.search('ol').first
    expect(ol).to_not be_nil, "Your <ol> tag is missing"
    expect(html_file_contents).to include('</ol>'), "Don't forget to include a closing </ol>"

    children = ol.children.select {|child| child.name == "li"}
    expect(children.length).to be >= 5
    expect(children[0].text).to match("Spread butter on bread and frying pan")
    expect(children[1].text).to match("Place bread in frying pan and fry")
    expect(children[2].text).to match("Add cheese on top of bread")
    expect(children[3].text).to match("Cover with second slice of bread")
    expect(children[4].text).to match("Turn over and fry for 2 minutes")

  end
end

**Comment by drakeltheryuujin** [comment] 2019-10-30 18:39
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Closed by drakeltheryuujin** 2019-10-30 18:39 UTC
